# Generated by Django 4.2.30 on 2026-09-02 05:40

from django.db import migrations, models
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ("repos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="embeddingchunk",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=3072, null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="access_token",
            field=models.TextField(blank=True, db_column="accessToken", null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar_url",
            field=models.URLField(blank=True, db_column="avatarUrl", null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_column="createdAt"),
        ),
        migrations.AlterField(
            model_name="user",
            name="github_id",
            field=models.CharField(
                blank=True, db_column="githubId", max_length=64, null=True, unique=True
            ),
        ),
    ]
